- name: "Install Packages"
  become: yes
  ansible.builtin.dnf:
    name:
      - git
      - wget
      - curl
      - vim
      - lsof
      - net-tools
      - iputils
      - jq
      - traceroute
      - unzip
      - "@nodejs:14/default"
      - kubernetes-client
      - libreswan
      - bind-utils
