- hosts: all

  vars_files:
    - .local.vars.yml
  
  roles:
    - role: base
      tags:
        - base
    - role: civo
      tags:
        - cloud
        - civo
    - role: gcp
      tags:
        - cloud
        - gcp
    - role: aws
      tags:
        - cloud
        - aws
    - role: workload_vm
      tags:
        - workload