- hosts: all

  vars_files:
    - vars.yml
  
  tasks:
  # roles:
  #   - role: base
  #     tags:
  #       - base
  #   - role: gcp
  #     tags:
  #       - cloud
  #       - gcp
  #   - role: aws
  #     tags:
  #       - cloud
  #       - aws
  #   - role: workload_vm
  #     tags:
  #       - workload