---
collections:
  - name: ansible.posix
    version: '1.2.0'
  - name: community.general
    version: '3.6.0'
  - name: kubernetes.core
    version: '2.0.0'
  - name: google.cloud 
    version: '1.0.2'