- hosts: localhost

  vars_files:
    - .local.vars.yml
  vars:
   civo_region: LON1
   civo_cluster_name: gloo-mgmt

  tasks:
    - debug:
        msg: "{{ eks_create | bool  }}"
    - debug:
        msg: "{{ eks_delete | bool  }}"       
    - debug:
        msg: "Delete ? {{ (eks_delete | bool) and not (eks_create | bool ) }}"