- name: "Create GCP Credentials folder"
  file:
    path: "{{ ansible_env.HOME }}/.config/gcloud"
    recurse: yes
    state: directory
    mode: "0744"
  when: create_gcp_credentials_file

- name: "Save GCP Credentials"
  copy:
    dest: "{{ ansible_env.HOME }}/.config/gcloud/credentials"
    content: |
      {{ lookup('file',lookup('env','GOOGLE_APPLICATION_CREDENTIALS')) }}
    mode: "0744"
  when: create_gcp_credentials_file | bool

- name: "Create VPC"
  include: network/vpc.yml
  when: ( gcp_create_vpc | bool ) and  not ( gcp_delete_vpc | bool)

- name: "Create Kubernetes Cluster"
  include: k8s/gke_cluster.yml
  when: ( gke_create | bool ) and not ( gke_delete | bool )

- name: "Delete Kubernetes Cluster"
  include: k8s/gke_cluster_rollback.yml
  when: ( gke_delete | bool ) and not ( gke_create | bool )

- name: "Create VPN"
  include: network/vpn.yml
  when: gcp_create_vpn  | bool

- name: "Delete VPN"
  include: network/vpn_rollback.yml
  when: not ( gcp_create_vpn | bool ) and ( gcp_delete_vpn | bool )

- name: "Delete VPC"
  include: network/vpc_rollback.yml
  when: not ( gcp_create_vpc | bool ) and ( gcp_delete_vpc | bool )