- name: "Download Istio"
  get_url:
    url: "https://github.com/istio/istio/releases/download/{{ istio_version }}/istio-{{ istio_version }}-linux-amd64.tar.gz"
    checksum: "sha256:fbd4d8bba838203c0f3631fb3699955ed3bd27802b0ab9ceb109c1fe337fa6d2"
    dest: "/tmp"
  tags:
   - istio

- name: "Extract Istio {{ istio_version }}"
  unarchive:
    src: "/tmp/istio-{{ istio_version }}-linux-amd64.tar.gz"
    dest: "{{ ansible_env.HOME }}"
    remote_src: yes
  register: istio_install
  tags:
   - istio

- name: "Update .bashrc"
  ansible.builtin.blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK Istio {{ istio_version }}"
    block: |
      PATH=~/istio-{{ istio_version }}/bin:$PATH
    dest: "{{ ansible_env.HOME }}/.bashrc"
  when: istio_install
  tags:
   - istio

- name: "Clean existing Istio VM files"
  include: clean_istio_vm_files.yml
  when: clean_istio_vm_files 

- name: "Create Istio Work Dir"
  file:
    path: "{{ istio_vm_workdir }}"
    recurse: True
    state: directory
  tags:
   - istio

- name: "Deploy Istio Operator"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: istio-operator
    api_version: v1
    kind: Namespace
    state: present
  tags:
    - istio

- name: "Deploy Istio Operator"
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: istio-operator
    chart_ref: "{{ ansible_env.HOME}}/istio-{{ istio_version }}/manifests/charts/istio-operator"
    release_namespace: istio-operator
    create_namespace: true
  tags:
    - istio

- name: "Deploy Istio"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    namespace: istio-system
    template:
      path: 'istio/istio-cr.yaml.j2'
  tags:
    - istio
