- name: "Ensure Kubeconfig folder"
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/.kube"
    mode: "0744"

- name: "Authenticate with GKE"
  ansible.builtin.command:
    argv:
      - gcloud
      - container
      - clusters
      - get-credentials 
      - "{{ gke_cluster_name }}"
      - "--region={{ gke_cluster_location }}"
  environment:
    KUBECONFIG: "{{ ansible_env.HOME }}/.kube/gke_{{ gke_cluster_name  }}.kubeconfig"
    GOOGLE_APPLICATION_CREDENTIALS: "{{ gcp_cred_file }}"
  changed_when: false

- name: "Get available kubeconfigs"
  find: 
    use_regex: yes
    patterns: ['^.*\.?[kube]?config$']
    paths: "{{ ansible_env.HOME }}/.kube"
  register: kubeconfigs_files

- name: "Join kubeconfig files"
  set_fact:
    kubeconfig: "{{ kubeconfigs_files | community.general.json_query(kubeconfig_json_query) | join(':') }}"
  when: kubeconfigs_files.files 

- debug:
   var: kubeconfig

- name: "Kubernetes check"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ item }}"
    kind: Node
  register: nodes
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: "{{ gcp_cred_file }}"
  loop: "{{ istio_kubernetes_contexts }}"

- debug:
    var: nodes
  
- fail: 
   msg: "checkpoint"
  
- name: "Download Istio"
  get_url:
    url: "https://github.com/istio/istio/releases/download/{{ istio_version }}/istio-{{ istio_version }}-linux-amd64.tar.gz"
    checksum: "sha256:fbd4d8bba838203c0f3631fb3699955ed3bd27802b0ab9ceb109c1fe337fa6d2"
    dest: "/tmp"
  tags:
   - istio

- name: "Extract Istio {{ istio_version }}"
  unarchive:
    src: "/tmp/istio-{{ istio_version }}-linux-amd64.tar.gz"
    dest: "{{ ansible_env.HOME }}"
    remote_src: yes
  register: istio_install
  tags:
   - istio

- name: "Update .bashrc"
  ansible.builtin.blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK Istio {{ istio_version }}"
    block: |
      ISTIO_HOME=~/istio-{{ istio_version }}
      PATH=$ISTIO_HOME/bin:$PATH
    dest: "{{ ansible_env.HOME }}/.bashrc"
  when: istio_install
  tags:
   - istio

- name: "Deploy Istio Operator"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: istio-operator
    api_version: v1
    kind: Namespace
    state: present
  tags:
    - istio

- name: "Deploy Istio Operator"
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: istio-operator
    chart_ref: "{{ ansible_env.HOME}}/istio-{{ istio_version }}/manifests/charts/istio-operator"
    release_namespace: istio-operator
    create_namespace: true
  tags:
    - istio

- name: "Deploy Istio"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    namespace: istio-system
    template:
      path: 'istio/istio-cr.yaml.j2'
  tags:
    - istio
