apiVersion: networking.mesh.gloo.solo.io/v1
kind: AccessPolicy
metadata:
  name: to-vm
  namespace: gloo-mesh
spec:
  sourceSelector:
  - kubeServiceAccountRefs:
      serviceAccounts:
        - name: vm-blue-green-canary
          namespace: vm-blue-green-canary
          clusterName: cluster1
        - name: checks-and-tests
          namespace: default
          clusterName: cluster1
        - name: checks-and-tests
          namespace: default
          clusterName: cluster2
        - name: istio-ingressgateway-service-account
          namespace: istio-system
          clusterName: cluster1
        - name: istio-ingressgateway-service-account
          namespace: istio-system
          clusterName: cluster2
  destinationSelector:
  - kubeServiceMatcher:
      namespaces:
      - vm-blue-green-canary
      labels:
        app: blue-green-canary