- name: "Install civo cli(Debian)"
  become: yes
  ansible.builtin.apt:
    deb: "https://github.com/civo/cli/releases/download/{{ civo_cli_version }}/civo_amd64.deb"
  when: ansible_os_family == "Debian"
  tags:
   - cloud
   - civo

- name: "Install civo cli(Red Hat)"
  become: yes
  ansible.builtin.dnf:
    name: "https://github.com/civo/cli/releases/download/{{ civo_cli_version }}/civo_amd64.rpm"
    disable_gpg_check: yes
  when: ansible_os_family == "RedHat"
  tags:
   - cloud
   - civo

- name: "Save Civo Credentials"
  ansible.builtin.command:
    argv:
      - civo
      - apikey
      - save 
      - default
      - "{{ civo_api_key }}"
  when: create_civo_credentials_file  | bool
  tags:
   - cloud
   - civo

- name: "Set Default civo API Key"
  ansible.builtin.command:
    argv:
      - civo
      - apikey
      - current 
      - default
  when: create_civo_credentials_file  | bool
  tags:
   - cloud
   - civo

- name: "Create k3s Cluster"
  include: k3s_create.yml
  when: (civo_create | bool) and not (civo_delete | bool)

- name: "Delete k3s Cluster"
  include: k3s_rollback.yml
  when: (civo_delete | bool) and not (civo_create | bool)