istio_version: "1.10.4"

istio_kubernetes_contexts:
 - cluster-1
 - cluster-2 
 
# Istio 
istio_enabled: yes
istio_vm_app: blue-green-canary
istio_vm_namespace: vm-blue-green-canary
istio_vm_workdir: "/home/{{ ansible_user }}/istio-vm/files"
istio_vm_service_account: vm-blue-green-canary
istio_cluster_network: bgc-network1
istio_vm_network: bgc-vm-network
istio_cluster: cluster1