
gcp_cred_kind: serviceaccount
create_gcp_credentials_file: yes
gcp_cred_file: "{{ ansible_env.HOME }}/.config/gcloud/credentials"

# VPC
gcp_create_vpc: yes
gcp_delete_vpc: no
gcp_vpc_name: kameshs-k8s-vpc
gcp_vpn_name: kameshs-site-to-site-vpn

# k8s
gke_create: yes
gke_delete: no
gke_cluster_name: kameshs-gloo-demos
gke_node_count: 3

# VPN
gcp_create_vpn: yes
gcp_delete_vpn: no
gcp_vpn_vpc: "{{ gcp_vpc_name }}"
gke_cluster_node_type: n1-standard-4
gke_cluster_node_disk_size: 500
gke_cluster_location: asia-south1-c
gke_cluster_node_size: 3

# Subnets
k8s_subnet_cidr: 172.16.0.0/28
k8s_pods_ip_range: 172.17.0.0/16
k8s_services_ip_range: 172.18.0.0/20

left_subnet: 192.168.0.0/16

# IPSec
enable_ipsec: false
ipsec_connection_name: gcp-gloo-demos
is_ikev2: "no"