################################################################
# START VPC 
################################################################
- name: "GCP::Create VPC"
  google.cloud.gcp_compute_network:
    name: "{{ gcp_vpc_name }}"
    auto_create_subnetworks: no
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: network
################################################################
# END VPC 
################################################################

################################################################
# START VPC  SUBNETS
################################################################
- name: "GCP::Create VPC Subnetwork {{ right_subnet }}"
  google.cloud.gcp_compute_subnetwork:
    name: "{{ gcp_vpc_name }}-172-25"
    network: "{{ network }}"
    ip_cidr_range: "{{ right_subnet }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    region: "{{ gcp_region }}"
    state: present
  register: network_subnet_172_25
################################################################
# END VPC  SUBNETS 
################################################################