- name: "Delete VPC"
  google.cloud.gcp_compute_network:
    name: "{{ gcp_vpc_name }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent
