apiVersion: v1
kind: Service
metadata:
  name: blue-green-canary
  labels:
    app: blue-green-canary
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 3000
  selector:
    app: blue-green-canary
