- include: ../network/vpc.yml

- name: "Set EKS Cluster Facts"
  set_fact:
    k8s_vpc_id: "{{ eks_k8s_vpc.vpc.id }}"
    k8s_vpc_cidr_block: "{{ eks_k8s_vpc.vpc.cidr_block }}"
    k8s_sg_gloo_group_id: "{{ eks_gloo_mesh_sg.group_id }}"
    k8s_private_subnet_ids: "{{ k8s_private_subnets | json_query('results[*].subnet.id') | list | join(',')}}"
    k8s_private_subnet_zones: "{{ k8s_private_subnets | json_query('results[*].subnet.availability_zone') | list }}"
    k8s_public_subnet_ids: "{{ k8s_public_subnets | json_query('results[*].subnet.id') | list | join(',')}}"
    k8s_public_subnet_zones: "{{ k8s_private_subnets | json_query('results[*].subnet.availability_zone') | list }}"

- name: "Distinct Zones"
  debug:
    msg: "{{ ( k8s_private_subnet_zones + k8s_public_subnet_zones ) | unique }}"

- name: "Create EKS Cluster  Config"
  ansible.builtin.template:
    src: "cluster.yaml.j2"
    dest: "{{ ansible_env.HOME }}/{{ eks_cluster_name }}-eks.yaml"
  register: eks_cluster_config

# TODO why this fails with STS Errors
# - name: "Create an EKS cluster"
#   ansible.builtin.command:
#     argv:
#      - eksctl
#      - create
#      - cluster
#      - --profile="dev"
#      - --config-file={{ eks_cluster_config.dest }}
#      - --kubeconfig={{ ansible_env.HOME }}/.kube/{{ eks_cluster_name }}_kubeconfig
#   register: eks_cluster

- name: "Public Subnets to be used"
  debug:
    var: k8s_public_subnet_ids

- name: "Private Subnets to be used"
  debug:
    var: k8s_private_subnet_ids

- name: "Create an EKS cluster"
  ansible.builtin.command:
    argv:
      - eksctl
      - create
      - cluster
      - --name={{ eks_cluster_name }}
      - "--region={{ aws_region }}"
      - "--vpc-public-subnets={{ k8s_public_subnet_ids }}"
      - "--vpc-private-subnets={{ k8s_private_subnet_ids }}"
      - "--nodegroup-name={{ eks_cluster_name }}-workers-large"
      - "--node-security-groups={{ k8s_sg_gloo_group_id  }}"
      - "--node-type={{ eks_cluster_node_instance_type }}"
      - "--version={{ kubernetes_version }}"
      - "--nodes={{ eks_cluster_node_size }}"
      - "--node-type={{ eks_cluster_node_instance_type }}"
      - '--tags="app=gloo"'
      - --kubeconfig={{ ansible_env.HOME }}/.kube/{{ eks_cluster_name }}_kubeconfig
  register: eks_cluster

- debug:
    msg: "{{ eks_cluster.stdout | community.general.jc('eksctl') }}"
