apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary
spec:
  selector:
    matchLabels:
      app: blue-green-canary
      version: canary
  template:
    metadata:
      labels:
        app: blue-green-canary
        version: canary
