namespace: blue-green-canary

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: ui-config
    files:
      - .env

resources:
- ../base

patches:
- path: canary.yaml
  target:
    kind: Deployment
  options:
    allowNameChange: true
