apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec:
  selector:
    matchLabels:
      app: blue-green-canary
      version: blue
  template:
    metadata:
      labels:
        app: blue-green-canary
        version: blue

