- name: "Kill Envoy"
  become: yes
  shell: "/usr/local/bin/killEnvoy.sh"
  register: kill_envoy_result
  tags:
   - istio
   - app
  
- name: "Restart Istio"
  become: yes
  service:
    name: istio
    state: restarted
  tags:
   - istio
   - app

- name: "Restart Blue Green Canary"
  become: yes
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: blue-green-canary.service
  tags:
   - app