- include: setup_RedHat.yml
  when: ansible_os_family == "RedHat"

- include: setup_Debian.yml
  when: ansible_os_family == "Debian"

- name: "Install Python Packages"
  ansible.builtin.pip:
    name: 
    - kubernetes>=12.0.0
    - boto
    - botocore
    - boto3
    - PyYAML


- name: "Install Kubernetes Tools"
  become: yes
  community.general.snap:
    classic: yes
    name: 
      - kubectl
      - helm