- include: setup_RedHat.yml
  when: ansible_os_family == "RedHat"

- include: setup_Debian.yml
  when: ansible_os_family == "Debian"

- name: "Install Python Packages"
  ansible.builtin.pip:
    name: 
    - kubernetes>=12.0.0
    - boto
    - boto3